steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/keerthanacicd/omd-dag-test', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/keerthanacicd/omd-dag-test']